-- =====================================================================
-- Export für die Abgabe (Supabase SQL Editor)
-- Ausführen → Ergebniszelle anklicken → kopieren → als supabase/export.sql
-- ins Repository committen.
-- =====================================================================
create or replace function pg_temp.export_project()
returns text language plpgsql as $$
declare
  schema_sql text;
  data_sql   text := '';
  t          record;
  chunk      text;
begin
  -- ---------- Schema ----------
  select string_agg(stmt, E'\n\n' order by ord, stmt) into schema_sql
  from (
    -- 1. Enum-Typen
    select 10 as ord, format('create type public.%I as enum (%s);', ty.typname,
      string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)) as stmt
    from pg_type ty
    join pg_enum e on e.enumtypid = ty.oid
    join pg_namespace n on n.oid = ty.typnamespace
    where n.nspname = 'public'
    group by ty.typname

    union all
    -- 2. Tabellen
    select 20, format(E'create table public.%I (\n%s\n);', c.relname,
      string_agg(format('  %I %s%s%s%s', a.attname,
        format_type(a.atttypid, a.atttypmod),
        case when a.attnotnull then ' not null' else '' end,
        case when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end,
        case a.attidentity when 'a' then ' generated always as identity'
                           when 'd' then ' generated by default as identity' else '' end
      ), E',\n' order by a.attnum))
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
    left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
    where n.nspname = 'public' and c.relkind = 'r'
    group by c.relname

    union all
    -- 3. Funktionen (ohne Supabase-eigene)
    select 30, pg_get_functiondef(p.oid) || ';'
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prokind = 'f'
      and pg_get_function_result(p.oid) <> 'event_trigger'
      and pg_get_userbyid(p.proowner) <> 'supabase_admin'

    union all
    -- 4. Constraints (PK, FK, UNIQUE, CHECK, EXCLUDE)
    select 40, format('alter table public.%I add constraint %I %s;',
      c.relname, con.conname, pg_get_constraintdef(con.oid))
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'

    union all
    -- 5. Indizes ohne Constraint
    select 50, pg_get_indexdef(i.indexrelid) || ';'
    from pg_index i
    join pg_class c on c.oid = i.indrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and not exists (select 1 from pg_constraint where conindid = i.indexrelid)

    union all
    -- 6. Views
    select 60, format(E'create or replace view public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true))
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'v'

    union all
    -- 7. Trigger
    select 70, pg_get_triggerdef(tr.oid) || ';'
    from pg_trigger tr
    join pg_class c on c.oid = tr.tgrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and not tr.tgisinternal

    union all
    -- 8. RLS aktivieren
    select 80, format('alter table public.%I enable row level security;', c.relname)
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity

    union all
    -- 9. RLS-Policies
    select 90, format('create policy %I on public.%I as %s for %s to %s%s%s;',
      policyname, tablename, permissive, cmd, array_to_string(roles, ', '),
      case when qual is not null then ' using (' || qual || ')' else '' end,
      case when with_check is not null then ' with check (' || with_check || ')' else '' end)
    from pg_policies
    where schemaname = 'public'
  ) ddl;

  -- ---------- Daten ----------
  for t in
    select c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r'
    order by c.relname
  loop
    execute format(
      'select string_agg(format(%L, row_to_json(x)), E''\n'') from public.%I x',
      format('insert into public.%I select * from json_populate_record(null::public.%I, %%L);', t.relname, t.relname),
      t.relname
    ) into chunk;

    if chunk is null then
      data_sql := data_sql || '-- ' || t.relname || E': keine Daten\n\n';
    else
      data_sql := data_sql || '-- ' || t.relname || E'\n' || chunk || E'\n\n';
    end if;
  end loop;

  return E'-- ============ SCHEMA ============\n\n'
      || coalesce(schema_sql, '-- keine Objekte im Schema public')
      || E'\n\n-- ============ DATEN ============\n\n'
      || data_sql;
end $$;

select pg_temp.export_project() as export_sql;
